#############################################################################
# Generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#  Jul 18, 2021 01:33:28 PM +07  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Absolute
}




proc vTclWindow.top44 {base} {
    global vTcl
    if {$base == ""} {
        set base .top44
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m45" -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1536x811+-6+0
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1540 845
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Google Dịch"
    vTcl:DefineAlias "$top" "window" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    text $top.tex45 \
        -background white -font {-family {Segoe UI} -size 15} \
        -foreground black -height 213 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 1350 -wrap word 
    $top.tex45 configure -font "-family {Segoe UI} -size 15"
    $top.tex45 insert end text
    vTcl:DefineAlias "$top.tex45" "txtSrc" vTcl:WidgetProc "window" 1
    label $top.lab47 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Transformers Movie} -size 24 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #ffffff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text Translator 
    vTcl:DefineAlias "$top.lab47" "lbTranslator" vTcl:WidgetProc "window" 1
    text $top.tex46 \
        -background #c0c0c0 -font {-family {Segoe UI} -size 15} \
        -foreground black -height 213 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 1350 -wrap word 
    $top.tex46 configure -font "-family {Segoe UI} -size 15"
    $top.tex46 insert end text
    vTcl:DefineAlias "$top.tex46" "txtDest" vTcl:WidgetProc "window" 1
    ttk::combobox $top.tCo48 \
        -textvariable cbSrc -foreground {} -background #ffffff -takefocus {} 
    vTcl:DefineAlias "$top.tCo48" "cbSelectLangSrc" vTcl:WidgetProc "window" 1
    label $top.lab49 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -foreground #ffffff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text {Select Language:} 
    vTcl:DefineAlias "$top.lab49" "Label2" vTcl:WidgetProc "window" 1
    button $top.but50 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #000000 -disabledforeground #a3a3a3 -foreground #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Nghe 
    vTcl:DefineAlias "$top.but50" "btListenSrc" vTcl:WidgetProc "window" 1
    label $top.lab54 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 15 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #ffffff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text {Created by Phu Phuc} 
    vTcl:DefineAlias "$top.lab54" "lbCredit" vTcl:WidgetProc "window" 1
    label $top.lab55 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -foreground #ffffff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text {Select Language:} 
    vTcl:DefineAlias "$top.lab55" "Label2_1" vTcl:WidgetProc "window" 1
    ttk::combobox $top.tCo56 \
        -textvariable cbDest -foreground {} -background {} -takefocus {} 
    vTcl:DefineAlias "$top.tCo56" "cbSelectLangDest" vTcl:WidgetProc "window" 1
    menu $top.m45 \
        -activebackground $vTcl(actual_gui_menu_analog) \
        -activeforeground #000000 -background $vTcl(actual_gui_menu_bg) \
        -font TkMenuFont -foreground $vTcl(actual_gui_menu_fg) -tearoff 0 
    button $top.but47 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #000000 -disabledforeground #a3a3a3 -foreground #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Nghe 
    vTcl:DefineAlias "$top.but47" "btListenDest" vTcl:WidgetProc "window" 1
    button $top.but48 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #000000 -disabledforeground #a3a3a3 -foreground #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Nói 
    vTcl:DefineAlias "$top.but48" "btSpeakSrc" vTcl:WidgetProc "window" 1
    button $top.but51 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #000000 -disabledforeground #a3a3a3 -foreground #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Sao chép} 
    vTcl:DefineAlias "$top.but51" "btCopySrc" vTcl:WidgetProc "window" 1
    button $top.but52 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #000000 -disabledforeground #a3a3a3 -foreground #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Dán 
    vTcl:DefineAlias "$top.but52" "btPasteSrc" vTcl:WidgetProc "window" 1
    button $top.but53 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #000000 -disabledforeground #a3a3a3 -foreground #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Hoán đổi ngôn ngữ} 
    vTcl:DefineAlias "$top.but53" "btLanguageSwap" vTcl:WidgetProc "window" 1
    button $top.but54 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #000000 -disabledforeground #a3a3a3 -foreground #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Sao chép} 
    vTcl:DefineAlias "$top.but54" "btCopyDest" vTcl:WidgetProc "window" 1
    button $top.but45 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #000000 -disabledforeground #a3a3a3 -foreground #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Xóa 
    vTcl:DefineAlias "$top.but45" "btRemoveSrc" vTcl:WidgetProc "window" 1
    button $top.but46 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #000000 -disabledforeground #a3a3a3 -foreground #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Dịch 
    vTcl:DefineAlias "$top.but46" "btTranslate" vTcl:WidgetProc "window" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tex45 \
        -in $top -x 80 -y 150 -width 1350 -relwidth 0 -height 213 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab47 \
        -in $top -x 600 -y 30 -width 283 -relwidth 0 -height 39 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tex46 \
        -in $top -x 80 -y 430 -width 1350 -relwidth 0 -height 213 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.tCo48 \
        -in $top -x 1260 -y 120 -width 169 -relwidth 0 -height 22 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab49 \
        -in $top -x 1140 -y 120 -width 106 -relwidth 0 -height 22 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.but50 \
        -in $top -x 80 -y 110 -width 97 -relwidth 0 -height 34 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab54 \
        -in $top -x 610 -y 700 -width 273 -relwidth 0 -height 31 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab55 \
        -in $top -x 1140 -y 400 -width 106 -relwidth 0 -height 22 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.tCo56 \
        -in $top -x 1260 -y 400 -width 169 -relwidth 0 -height 22 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.but47 \
        -in $top -x 80 -y 390 -width 97 -height 34 -anchor nw \
        -bordermode ignore 
    place $top.but48 \
        -in $top -x 190 -y 110 -width 97 -height 34 -anchor nw \
        -bordermode ignore 
    place $top.but51 \
        -in $top -x 430 -y 110 -width 97 -height 34 -anchor nw \
        -bordermode ignore 
    place $top.but52 \
        -in $top -x 540 -y 110 -width 97 -height 34 -anchor nw \
        -bordermode ignore 
    place $top.but53 \
        -in $top -x 960 -y 110 -width 157 -relwidth 0 -height 34 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but54 \
        -in $top -x 430 -y 390 -width 97 -height 34 -anchor nw \
        -bordermode ignore 
    place $top.but45 \
        -in $top -x 650 -y 110 -width 97 -height 34 -anchor nw \
        -bordermode ignore 
    place $top.but46 \
        -in $top -x 760 -y 110 -width 97 -height 34 -anchor nw \
        -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}



set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top44 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

